"""empty message

Revision ID: 154a76a60997
Revises: a35833d7d25e
Create Date: 2023-12-26 18:00:17.939947+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154a76a60997'
down_revision: Union[str, None] = 'a35833d7d25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_note_user_id', 'note', type_='unique')
    op.create_unique_constraint(op.f('uq_note_title'), 'note', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_note_title'), 'note', type_='unique')
    op.create_unique_constraint('uq_note_user_id', 'note', ['user_id'])
    # ### end Alembic commands ###
