"""empty message

Revision ID: 00797983a8a0
Revises: 154a76a60997
Create Date: 2023-12-30 13:38:46.552986+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00797983a8a0'
down_revision: Union[str, None] = '154a76a60997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_note_title', 'note', type_='unique')
    op.create_unique_constraint('uix_title_user_id', 'note', ['user_id', 'title'])
    op.drop_constraint('uq_tag_user_id', 'tag', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tag_user_id', 'tag', ['user_id'])
    op.drop_constraint('uix_title_user_id', 'note', type_='unique')
    op.create_unique_constraint('uq_note_title', 'note', ['title'])
    # ### end Alembic commands ###
