"""empty message

Revision ID: 936ff13c5b86
Revises: 00797983a8a0
Create Date: 2024-01-02 23:29:49.200955+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936ff13c5b86'
down_revision: Union[str, None] = '00797983a8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tag_user_id_user', 'tag', type_='foreignkey')
    op.drop_column('tag', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_tag_user_id_user', 'tag', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
