"""empty message

Revision ID: 65045282678b
Revises: 936ff13c5b86
Create Date: 2024-01-08 15:30:45.305325+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65045282678b'
down_revision: Union[str, None] = '936ff13c5b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vk_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('ds_id', sa.Integer(), nullable=True))
    op.alter_column('user', 'tg_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_user_username', 'user', type_='unique')
    op.create_index(op.f('ix_user_ds_id'), 'user', ['ds_id'], unique=True)
    op.create_index(op.f('ix_user_vk_id'), 'user', ['vk_id'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_vk_id'), table_name='user')
    op.drop_index(op.f('ix_user_ds_id'), table_name='user')
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    op.alter_column('user', 'tg_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'ds_id')
    op.drop_column('user', 'vk_id')
    # ### end Alembic commands ###
