"""empty message

Revision ID: 07257f24bc76
Revises: 65045282678b
Create Date: 2024-01-09 15:42:46.888731+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07257f24bc76'
down_revision: Union[str, None] = '65045282678b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_title_user_id', 'note', type_='unique')
    op.drop_constraint('fk_note_user_id_user', 'note', type_='foreignkey')
    op.create_foreign_key(op.f('fk_note_user_id_user'), 'note', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.drop_constraint('fk_notes_tags_note_id_note', 'notes_tags', type_='foreignkey')
    op.drop_constraint('fk_notes_tags_tag_id_tag', 'notes_tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notes_tags_note_id_note'), 'notes_tags', 'note', ['note_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(op.f('fk_notes_tags_tag_id_tag'), 'notes_tags', 'tag', ['tag_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notes_tags_tag_id_tag'), 'notes_tags', type_='foreignkey')
    op.drop_constraint(op.f('fk_notes_tags_note_id_note'), 'notes_tags', type_='foreignkey')
    op.create_foreign_key('fk_notes_tags_tag_id_tag', 'notes_tags', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key('fk_notes_tags_note_id_note', 'notes_tags', 'note', ['note_id'], ['id'])
    op.drop_constraint(op.f('fk_note_user_id_user'), 'note', type_='foreignkey')
    op.create_foreign_key('fk_note_user_id_user', 'note', 'user', ['user_id'], ['id'])
    op.create_unique_constraint('uix_title_user_id', 'note', ['user_id', 'title'])
    # ### end Alembic commands ###
